[package]
name = "cursive-backend-wasm"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cursive = { git = "https://github.com/Riey/cursive", branch = "wasm", default-features = false }
wasm-bindgen = "0.2.51"
js-sys = "0.3.28"
unicode-width = "0.1.6"

[dependencies.web-sys]
version = "0.3.28"
features = [
    "console",
    "Window",
    "Document",
    "Node",
    "Element",
    "EventTarget",
    "HtmlElement",
    "HtmlDivElement",
    "HtmlSpanElement",
    "HtmlInputElement",
    "CssStyleDeclaration",
    "CompositionEvent",
    "MouseEvent",
    "TouchEvent",
    "TouchList",
    "Touch",
    "KeyboardEvent",
]

[dev-dependencies]
wasm-bindgen-test = "0.2"
