name: ci

on:
  push:
    paths:
      - .github/workflows/ci.yml
      - src/**
      - Cargo.toml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup wasm
      run: rustup target add wasm32-unknown-unknown
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build
      run: wasm-pack build
    - name: Run tests
      run: wasm-pack test --firefox
